on:
  push:
    branches: "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jodersky/setup-mill@v0.2.3
      with:
        mill-version: 0.9.3
    - name: compile the project
      run: mill ulang.compile
    - name: Run tests
      run: mill ulang.test
